### ISSUE TITLE
Not able to populate the database!

### ISSUE THREAD

**Issue by hikmatune** [andreynovikov/galleria#5]
Hey Andrey,
How do I populate the database using local images?
Thanks,

**Comment by hikmatune** [comment]
I found it, just had to insert the folders.
INSERT INTO image(bundle) VALUES('/2019/January');
INSERT INTO image(bundle) VALUES('/2019/February');
INSERT INTO image(bundle) VALUES('/2019/March');
INSERT INTO image(bundle) VALUES('/2019/April');
INSERT INTO image(bundle) VALUES('/2019/May');
INSERT INTO image(bundle) VALUES('/2019/June');
INSERT INTO image(bundle) VALUES('/2019/July');
INSERT INTO image(bundle) VALUES('/2019/August');
INSERT INTO image(bundle) VALUES('/2019/September');
INSERT INTO image(bundle) VALUES('/2019/October');
INSERT INTO image(bundle) VALUES('/2019/November');
INSERT INTO image(bundle) VALUES('/2019/December');

on the requirements i had to change python-magic~=0.4.14

**Comment by andreynovikov** [comment]
Database should be auto populated when you first access the bundle path from browser (type it directly in URL).
